let products = [
    { product_id:1,
      product_name: "nail polish",
      product_img: "./Ii.jpg",
      product_img1: "./Nn.jpg",
      product_img2: "./Yy.jpg",
      product_img3: "./Hu.jpg",
      description:". .",
      category: "topwear",
      price: "25 pound ",
    },
    {   product_id:2,
      product_name: "nails",
      product_img: "./Ws.jpg",
      product_img1: "./Rr.jpg",
      product_img2: "./Wed.jpg",
      product_img3: "./09i.jpg",
      description:". .",
      category: "topwear",
      price: " 25 pound ",
    },
    {   product_id:3,
      product_name: "nail polish",
      product_img: "./Gh.jpg",
      product_img1: "./Km.jpg",
      product_img2: "./Jkk.jpg",
      product_img3: "./Rgg.jpg",
      description:`
      Button collar
      Oxford fabric
      One chest pocket`,
      category: "",
      price: "25 pound ",
    },
    {   product_id:4,
      product_name: "nail",
      product_img: "./J.jpg",
      product_img1: "./R.jpg",
      product_img2: "./Ghj.jpg",
      product_img3: "./Dffv.jpg",
      description:` .`,
      category: "nail",
      price: "25 ",
    },
    {   product_id:5,
      product_name: "nail polish",
      product_img: "./Dffv.jpg",
      description:`nail`,
      category: "",
      price: "25",
    },
    {   product_id:6,
      product_name: "nail",
      product_img: "./Dfg.jpg",
      product_img1: "./Efff.jpg",
      description:`
      nail `,

      category: "nail polish",
      price: "25 ",
    },

    {   product_id:7,
        product_name: "Nail polish",
        product_img: "./Gbhh.jpg",
        product_img1: "./Fgb.jpg",
        product_img2: "./Ggbnnj.jpg",
        product_img3: "./Tgh.jpg",
        description:`nails`,
        category: "nail polish",
        price: "25 ",
      },
    {   product_id:8,
      product_name: "nail polish",
      product_img: "./Fff.jpg",
      description:" nail polish",
      category: "nail polish",
      price: "25 ",
    },
    {   product_id:9,
        product_name: "nail polish",
        product_img: "./Ffjif.jpg",
        description:"nail polish",
        category: "nails",
        price: "25 ",
      },
      {   product_id:10,
        product_name: "nail polish",
        product_img: "./Cvbhh.jpg",
        description:"nail polish",
        category: "nail polish",
        price: "25 ",
      },
      {   product_id:11,
        product_name: "nail ",
        product_img: "./Fghj.jpg",
        description:"nail polish",
        category: "nails",
        price: "25 ",
      },

    {   product_id:12,
        product_name: "nail polish",
        product_img: "./Ctctvv.jpg",
        product_img1: "./Rd5ct.jpg",
        product_img2: "./Hji.jpg",
        product_img3: "./Rgb.jpg",

        description:`nail `,
        category: "Nail polish",
        price: "25 ",
      },

    {   product_id:13,
        product_name: "nail polish",
        product_img: "./Dcf.jpg",
        product_img1: "./Bhhh.jpg",
        product_img2: "./Hjygj.jpg",
        product_img3: "./Ghhnjj.jpg",
        description:`nail  polish `,
        category: "Nail polish",
        price: "25 ",
    },
    {   product_id:14,
      product_name: "nail polish",
      product_img: "./Vbby.jpg",
      product_img1: "./Dccvf.jpg",
      product_img2: "./Erfvg.jpg",
      product_img3: "./Ghhjj.jpg",
      description:` Nail  polish `,
      category: "Nail polish",
      price: "25",
    },
    {   product_id:15,
      product_name: "Nail polish",
      product_img: "./Hjjiii.jpg",
      description:"Nail Polish",
      category: "Nail polish",
      price: "25",
    },
   
  ];

