let products = [
    { product_id:1,
      product_name: "nail polish",
      product_img: "  https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTt401he1KjfYROoW3VCH_wcnGZK_8Wems9g&usqp=CAU  ",
      product_img1: "./Vbby.jpg",
      product_img2: "./Nn.jpg",
      product_img3: "./li.jpg",
      description:"Nail polish.",
      category: "topwear",
      price: "25",
    },
    {   product_id:2,
      product_name: "Nail polish",
      product_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9ZNRM0XpYExzicCiFGkD0AAkU61ASFT5UEw&usqp=CAU  ",
      product_img1: "./Wed.jpg",
      product_img2: "./Ggbnnj.jpg",
      product_img3: "./Km.jpg",
      description:". nail polish.",
      category: "topwear",
      price: "25",
    },
    {   product_id:3,
      product_name: "Nail polish",
      product_img: " https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT61Jd2Aa-6F-sxlgPAWJ4ylGZm_S_kAQIUGw&usqp=CAU  ",
      product_img1: "./Gbhh.jpg",
      product_img2: "./Rr.jpg",
      product_img3: "./Ggbnnj.jpg",
      description:`
      Button collar
      Oxford fabric
      One chest pocket`,
      category: "topwear",
      price: "25 ",
    },
    {   product_id:4,
      product_name: "Nail polish",
      product_img: "  https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTuM0Pf4r1bYDDK4WV5J7qnckLG2X-VQAAZQ&usqp=CAU  ",
      product_img1: "./Fff.jpg",
      product_img2: "./Gh.jpg",
      product_img3: "./Ws.jpg",
      description:` .`,
      category: "nail polish",
      price: " 25",
    },
    {   product_id:5,
      product_name: "Nail polish",
      product_img: "./Fgb.jpg",
     product_img1: "./Hu.jpg",
     product_img2: "  https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRC7HR61jN4S0Hqe1EApaHYp9UfRAcaK2bfjg&usqp=CAU  ",
      description:``,
      category: "bottomwear",
      price: "25",
    },
    {   product_id:6,
      product_name: "Nail polish",
      product_img: " https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT59qRAKK8JFkacz2EnEvDozzLsDUiELSx46w&usqp=CAU  ",
      product_img1: "./Hu.jpg",
     product_img2: "./Ghj.jpg",
     product_img2: "./Rgg.jpg",
      description:``,

      category: "bottomwear",
      price: " 25",
    },

    {   product_id:7,
        product_name: "Nail polish",
        product_img: "  https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnoQet5rH729NoPvSTf2hPxSDXfuR1Z7lsCg&usqp=CAU ",
        product_img1: "./Y.jpg",
        product_img2: "./Lk.jpg",
        product_img3: "./Hjygj.jpg",
        description:`
        `,
        category: "topwear",
        price: "25",
      },
    {   product_id:8,
      product_name: "Nail polish",
      product_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3hCrnWZCZDvP6ZNSlgPiOOM7B-WwuBf5G6Q&usqp=CAU ",
      product_img1: "./Nn.jp6",
     product_img2: "./li.jpg",
     description:"",
      category: "shoes",
      price: "25 ",
    },
    {   product_id:9,
        product_name: "Nail polish",
        product_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3kpJQMrqvl063ppUXuYIFZufAnbTuDrXePQ&usqp=CAU ",
       product_img1: "./Rr.jpg",
     product_img2: "./Ggbnnj.jpg",
     description:"",
        category: "shoes",
        price: "25",
      },
      {   product_id:10,
        product_name: "Nail polish",
        product_img: " https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgPfj9zf4C0FNQelBau-5gOlQK-dBe1Syc0w&usqp=CAU  ",
       product_img1: "./Rr.jpg",
       product_img2: "./Gbhh.jpg",
        description:"",
        category: "shoes",
        price: "25 ",
      },
      {   product_id:11,
        product_name: "Nail polish",
        product_img: "  https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6YuQbkswEGvsAUPRPfjYmqqc_R7UK-qrvNg&usqp=CAU  ",
       product_img1: "./Erfvg.jpg",
       product_img2: "./Ghhjj.jpg",
        description:"",
        category: "shoes",
        price: " 25",
      },

    {   product_id:12,
        product_name: "",
        product_img: "images/p/p71.jpg",
        product_img1: "images/p/p72.jpg",
        product_img2: "images/p/p73.jpg",
        product_img3: "images/p/p74.jpg",

        description:`Crew Neck Regular Long Sleeve Women's Tricot Sweater
        Ribbed ankles and bottom`,
        category: "topwear",
        price: "",
      },

    {   product_id:13,
        product_name: " ",
        product_img: "images/p/p53.jpg",
        product_img1: "images/p/p54.jpg",
        product_img2: "images/p/p51.jpg",
        product_img3: "images/p/p52.jpg",
        description:`Waistband
        Front double pocket
        made of stamp fabric`,
        category: "jacket",
        price: " ",
    },
    {   product_id:14,
      product_name: "",
      product_img: "images/p/p31.jpg",
      product_img1: "images/p/p32.jpg",
      product_img2: "images/p/p33.jpg",
      product_img3: "images/p/p34.jpg",
      description:`Crew Neck Short Sleeve Combed Cotton Men's T-shirt From combed cotton fabric short sleeved T-Shirt`,
      category: "topwear",
      price: "",
    },
    {   product_id:15,
      product_name: "",
      product_img: "images/products/p6.PNG",
      description:"wonderful half-boot",
      category: "shoes",
      price: " ",
    },
   
  ];

